### ISSUE TITLE
Error Start App from Launchpad

### ISSUE THREAD

**Issue by Th0masMa** [abap2UI5/abap2UI5-launchpad_on_premise#3]
Hi @oblomov-dev ,

if i start the app from Launchpad i receice an error

![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/64013300/58903dc6-f484-4836-accd-8a48ba7c01cb)

Launchpad Configuration

![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/64013300/46da204b-ad6d-46b8-90c1-fa8e5708ffe2)

![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/64013300/8920968d-501f-4d76-940b-6ee7fdeed872)

What do i wrong?

Best Regards
Thomas

**Comment by oblomov-dev** [comment]
Mhh starting the app independently is working on your system?

How described in the documentation or here:
![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/102328295/a00641a0-aba1-4ffd-903c-dc85d9e7e957)

**Comment by Th0masMa** [comment]
I can start the service from sicf. It works fine.

**Comment by oblomov-dev** [comment]
Ok great! First step done. Then it is just a problem with the launchpad maintenance, will try to give it a look again and extend the documentation in the next days.

**Comment by Th0masMa** [comment]
Thank you very much. Have a nice Weekend.

**Comment by oblomov-dev** [comment]
Checked it again, basically we now have a normal UI5 app and just need to customize the on-premise launchpad in the normal way. Check out the following documentation:
https://github.com/abap2UI5/abap2UI5-documentation/blob/main/docs/ext-fiori_launchpad_integration/launchpad_setup.md

Or this guideline:
https://blogs.sap.com/2017/11/19/sap-fiori-ui5-app-configuration-in-sap-fiori-launchpad/

Let me know if there are any problems, did not find the time to do the whole configuration on the system by myself.

**Comment by oblomov-dev** [comment]
Ok the UI5 library now gets loaded from the launchpad sources, seems that certain modules (Date) are not available. Not sure if this is a abap2UI5 specific problem or a general one. I will try to check this on my own system.

**Comment by oblomov-dev** [comment]
Customized it to the end and also get an error but another one:
<img width="500" alt="image" src="https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/102328295/b6f7562d-3987-4c53-9f8e-391320a044e0">

Seems to be very dependent of the UI5 version the launchpad uses. Which UI5 version is your launchpad using?

**Comment by Th0masMa** [comment]
SAPUI5 Distribution: 1.96.12 (Build von 24.08.2022 08:04:00)
OpenUI5 Version: 1.96.11 (Build von 22.08.2022 08:47:00)
Benutzeragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
App-URL: https:<hostname>:8001/sap/bc/ui5_ui5/ui2/ushell/shells/abap/Fiorilaunchpad.html?sap-client=500&sap-language=DE#Shell-home

Important

![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/64013300/8b314518-1dec-4024-8ef5-8097d9755f17)

![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/64013300/9ad15fc6-6f6f-4eac-9165-09e19842e67c)

**Comment by oblomov-dev** [comment]
Ok you customize the tile different, now did it like you:
<img width="600" alt="image" src="https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/102328295/13825f8e-f10d-4d98-abfd-4886b173fc50">
<img width="600" alt="image" src="https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/102328295/d618bb64-e4f1-4db3-82cc-ab10c188e8b9">
<img width="600" alt="image" src="https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/102328295/6ec44cbd-2408-47e8-991b-9ed1c31d08fa">
But get the same error, although i checked the ID.

I am not really an on-premise launchpad expert, normally just doing cloud launchpad so i am wondering a little bit how this is working. For me this is not a specific abap2UI5 problem because i just deployed a normal UI5 app 🤷‍♂️

@Th0masMa besides all this, i added a changes to abap2UI5 yesterday and this error should not occur anymore. 
<img width="600" alt="image" src="https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/102328295/9319cb49-ea4e-4bb7-9800-a351c72b6019">

So you can check this again.

Best regards.

**Comment by Th0masMa** [comment]
Hi @oblomov-dev ,
I test the new Version. It works.
Thomas

**Comment by oblomov-dev** [comment]
Cool! nice to hear that this is working now. 

If you have the chance to share more screenshots of your configuration & transactions you customized etc. Feel free to share it, it would be a big help.
There are a lot of tutorial concerning this but i can not really find out which guidelines are working and what to do exactly. I can give it a try then again.

best regards.

**Comment by oblomov-dev** [comment]
HI @axelmohnen,

yes in the HTTP_GET the lt_config is still filled, but it does not have any effect to the frontend app (there it is ignored). I don't want to have two abap2UI5 versions, therefore i keep it as it is. You can also delete it but i would not recommend this. With the next update of abap2UI5 it will be overwritten again anyway.

You enhancement with the title is a nice idea. Can you send a PR with your adjustment to the manifest and controller?

Fullscreen mode:
What does this mean for you? You want to start an app in a separated tab? I think this is also configurable via launchpad. You have to start the app via external URL.

Best regards.

**Comment by axelmohnen** [comment]
With fullscreen mode I mean the "letterboxing".
[https://experience.sap.com/fiori-design-web/letter-boxing/]

In the manifest of the ZABAP2UI5 app I could set the property "sap.ui.fullWidth: true/false" in order to switch letterboxing on/off.

**Comment by oblomov-dev** [comment]
Ah ok I'm most of the apps it is set manually maybe this overwrites the functionality. Did you check if the called app sets a shell? If yes maybe delete this control and try again.

**Comment by axelmohnen** [comment]
How do you can set the letterboxing manually in the app?

**Comment by oblomov-dev** [comment]
letterboxing is created when you use the control Shell, for example here:
https://github.com/abap2UI5/abap2UI5/blob/d4afaffed4f57a9c75891e0932e36a0afeb97edc/src/z2ui5_cl_app_hello_world.clas.abap#L33

Delete this line and your app should be in fullscreen mode.

**Comment by axelmohnen** [comment]
Unfortunately, it doesn't work. 
It seems the shell of the SAPUI5 app overwrites it. The ZABAP2UI5 "view1" doesn't have a "shell" control implemented (only <mvc:View>)

**Comment by oblomov-dev** [comment]
mhh wenn i delete line 33 and start the app, directly or with the new zabap2ui5, in both cases letterboxing is deactivated:
![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/102328295/9a5e7221-b843-46f4-86e7-1003a64e18dc)

**Comment by axelmohnen** [comment]
Could you please compare my elements with yours.
In my case the width is always set to 80rem. 
![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/22371169/b0e854c8-100a-4120-b5c3-4cd3d247bb31)

![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/22371169/ed389129-5a7d-417b-ae82-08b687163307)

**Comment by axelmohnen** [comment]
Hi @oblomov-dev,

problem has been solved.
I added the property "fullWidth=true" to the manifest.
Now I'm able to activate/deactivate letterboxing by adding/remove the "SHELL()" method.
![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/22371169/b1e0ddd3-2416-4c55-b89d-3976475eb85e)

Thanks,
Axel

**Comment by oblomov-dev** [comment]
Cool, nice to hear that it works now!

Unfortunately i have problems to add the app to my own on-premise launchpad, get an error when starting the app. So if you have the time feel free to share screenshots of the configurations you made. Maybe i took the wrong tutorial or made a mistake somewhere.
https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/issues/3#issuecomment-1683400161

Thanks and best regards.

**Comment by axelmohnen** [comment]
Here is the target mapping:
![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/22371169/fef0e572-b9b6-4d61-9e0c-90dac3820942)

and the corresponding tile configuration:
![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/22371169/38f87ea3-844f-44bb-8665-d2e6dc83bacb)

**Comment by oblomov-dev** [comment]
i clos this one, just open a new issue if there are further problems
