### ISSUE TITLE
Error on start of main app

### ISSUE THREAD

**Issue by Theizo-ATP** [abap2UI5/abap2UI5-launchpad_on_premise#6]
When starting the app using 'Test Service' the app is starting but whitout the 'Hello World'-start app, just a blank page.

I have followed the [instructions](https://github.com/abap2UI5/abap2UI5-documentation/blob/main/docs/ext-fiori_launchpad_integration/installation.md) to the letter :(

![image](https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/147174371/ae4db712-73ff-4fd9-b6b0-3090ea2a2fed)

**Comment by oblomov-dev** [comment]
Hi @Theizo-ATP,
depending on your system/launchaps you will get some errors in the console. I also have the ShellUIService Errors but it is still working on my end:
<img width="500" alt="image" src="https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/102328295/474ed9be-a3e9-43b9-8641-fa5b2364d8be">

<img width="200" alt="image" src="https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/assets/102328295/25488bf3-4a75-48c0-841f-d14e27a5f04f">

Which UI5  version are you using? Do you use the local UI5 version of you abap system? My test war working with the following index.html:
https://github.com/abap2UI5/ext-fiori_launchpad_on_premise/blob/4ab7ff8750782a09fe48e981ce3f31d78dcce164/src/zabap2ui5.wapa.index.html#L15

**Comment by oblomov-dev** [comment]
i close this one, just open a new issue of you have further problems.
